mapp_project : mapp_project_00016
mapp_batch : mapp_batch_00034
met_annot_enhancer_folder : mapp_batch_00034
gnps_job_id : 3aa60b6233c84abb9ceda7087b9cca78

dataset_experiment : 
  name: "mapp_batch_00034 LCMS metabolomics dataset"
  description: "Ola and Alisson bioactive Strepto"

paths:
  docs: '/Users/pma/Dropbox/git_repos/mapp-metabolomics-unit/laure-weisskopf-group/docs'
  output: '/Users/pma/Dropbox/git_repos/mapp-metabolomics-unit/laure-weisskopf-group/docs/mapp_project_00016/mapp_batch_00034/pos/results/stats/nochebi' # Not mandatory, default is in the stats subdirectory

polarity: "pos"
ms_files_extension: ".mzML"

filenames:
  sirius_annotations: compound_identifications.tsv
  canopus_annotations: canopus_compound_summary.tsv
  gnps_graphml: 6fda6b8106e9400e8a52ac53ee50d642.graphml


actions:
  scale_data : TRUE
  filter_sample_type : TRUE
  filter_sample_metadata_one : FALSE
  filter_sample_metadata_two : FALSE
  filter_variable_metadata_one : FALSE
  filter_variable_metadata_two : FALSE
  filter_features : FALSE
  run_PLSDA : FALSE
  calculate_multi_series_fc : FALSE

filter_sample_type :
  mode : 'include'
  factor_name : 'sample_type'
  levels : 'sample' 

filter_sample_metadata_one :
  mode : 'exclude'
  factor_name : 'ATTRIBUTE_condition'
  levels : 
     - 'C'
     - 'HN'
     - 'WT'

filter_sample_metadata_two :
  mode : 'exclude'
  factor_name : 'filename'
  levels :
     - '20221109_PMA_MAPP_01_22_033_neg_post_01.mzML'
     - '20221109_PMA_MAPP_01_22_033_neg_post_02.mzML'

filter_variable_metadata_one :
  mode : 'include'
  factor_name : 'NPC.pathway_canopus'
  levels : 'Fatty acids' # E.g. One of "Alkaloids", "Amino acids and Peptides", "Terpenoids", "Fatty acids", "Carbohydrates", "Polyketides", "Shikimates and Phenylpropanoids" for levels if you use factor_name : 'NPC.pathway_canopus'

filter_variable_metadata_two :
  mode : 'include'
  factor_name : 'NPC.pathway_canopus'
  levels : 'Fatty acids' 


colnames:
  to_combine: 
     - "ATTRIBUTE_Activity"

  to_output:
     - "ATTRIBUTE_Activity"


multi_series:
  colname: 'time.point'
  points:
     - '00'
     - '04'
     - '08'
     - '12'
     - '16'
     - '20'

     
filters:
  metadata_variable: "ATTRIBUTE_Activity" # This variable will be used throughout the whole script

boxplot:
  topN : 16 # N for TopN boxplots to output 

posthoc:
  p_value: 0.05 # p-Value for filtering th RF inputs

heatmap:
  topN : 100 # N for TopN features to output in the heatmap


feature_to_filter :
    - '3298_214.19_6.5'
    - '3311_252.18_4'
    - '1630_229.19_7.6'
    - '1638_214.19_6.5'