mapp_project : mapp_project_00007
mapp_batch : mapp_batch_00020
met_annot_enhancer_folder : mapp_batch_00020
gnps_job_id : dbb61f53ca4e4ab8bac13d4662aadd8e

dataset_experiment : 
  name: "mapp_batch_00020 LCMS metabolomics dataset"
  description: "Didier reinhardt Medicago Nodules HILIC Metabo pos "

paths:
  docs: '/Users/pma/Dropbox/git_repos/mapp-metabolomics-unit/didier-reinhardt-group/docs'
  output: '/Users/pma/Dropbox/git_repos/mapp-metabolomics-unit/didier-reinhardt-group/docs/mapp_project_00007/mapp_batch_00020/pos/results/stats' # Not mandatory, default is in the stats subdirectory

actions:
  scale_data : TRUE
  filter_sample_type : TRUE
  filter_sample_metadata_one : TRUE
  filter_sample_metadata_two : FALSE
  filter_variable_metadata_one : TRUE
  filter_variable_metadata_two : FALSE
  filter_features : FALSE
  run_PLSDA : TRUE
  calculate_multi_series_fc : FALSE

filter_sample_type :
  mode : 'include'
  factor_name : 'sample_type'
  levels : 'sample' 

filter_sample_metadata_one :
  mode : 'exclude'
  factor_name : 'condition'
  levels : 
      - 'C'
      # - 'HN'
      - 'NifH'

filter_sample_metadata_two :
  mode : 'exclude'
  factor_name : 'condition'
  levels : 'C'

filter_variable_metadata_one :
  mode : 'include'
  factor_name : 'NPC.pathway_canopus'
  levels : 'Fatty acids' # E.g. One of "Alkaloids", "Amino acids and Peptides", "Terpenoids", "Fatty acids", "Carbohydrates", "Polyketides", "Shikimates and Phenylpropanoids" for levels if you use factor_name : 'NPC.pathway_canopus'

filter_variable_metadata_two :
  mode : 'include'
  factor_name : 'NPC.pathway_canopus'
  levels : 'Fatty acids' 


polarity: "pos"
ms_files_extension: ".mzML"

filenames:
  sirius_annotations: compound_identifications.tsv
  canopus_annotations: canopus_compound_summary.tsv
  gnps_graphml: 27ac08b3bd43408c8d7f6a8e42d51cb9.graphml

colnames:
  to_combine: 
     - "condition"
     - "condition_detailed"

  to_output:
     - "condition"


to_combine_horizontally:
  # column1: 
  #   name: "condition"
  #   groups:
  #     # group1: 
  #     #   name: "HN_WT"
  #     #   cols: 
  #     #   - "HN"
  #     #   - "WT"
  #     group2: 
  #       name: "NifH_Argon_HN"
  #       cols: 
  #       - "NifH"
  #       - "Argon"
  #       - "HN"
  # column2: 
  #   name: "sample_type"
  #   groups:
  #     group1: 
  #       name: "sample_QC"
  #       cols: 
  #       - "sample"
  #       - "QC"

multi_series:
  colname: 'time.point'
  points:
     - '00'
     - '04'
     - '08'
     - '12'
     - '16'
     - '20'

filters:
  metadata_variable: "condition" # This variable will be used throughout the whole script

boxplot:
  topN : 16 # N for TopN boxplots to output 

posthoc:
  p_value: 0.05 # p-Value for filtering th RF inputs

heatmap:
  topN : 100 # N for TopN features to output in the heatmap


feature_to_filter :
    - '3298_214.19_6.5'
    - '3311_252.18_4'
    - '1630_229.19_7.6'
    - '1638_214.19_6.5'