mapp_project : mapp_project_00021
mapp_batch : mapp_batch_00037
met_annot_enhancer_folder : mapp_batch_00037
gnps_job_id : 6c2d9529be2c4784a85b80cab7576935

dataset_experiment : 
  name: "mapp_batch_00037 LCMS metabolomics dataset"
  description: "Andrea Brenna"

actions:
  scale_data : TRUE
  filter_variable_metadata : TRUE
  filter_sample_metadata : TRUE

filter_variable_metadata :
  mode : 'include'
  factor_name : 'NPC.pathway_canopus'
  levels : 'Terpenoids'

filter_sample_metadata :
  mode : 'include'
  factor_name : 'sample_type'
  levels : 'sample'

paths:
  docs: '/Users/pma/Dropbox/git_repos/mapp-metabolomics-unit/andrea-brenna-group/docs'

polarity: "pos"
ms_files_extension: ".mzML"

filenames:
  sirius_annotations: compound_identifications.tsv
  canopus_annotations: canopus_compound_summary.tsv
  gnps_graphml: 7aa7f1801b564637aa5848c99367d1d4.graphml

colnames:
  to_combine: 
     - "age"
     - "genotype"

  to_output:
     - "age"
     - "genotype"
     - "age_genotype"
     
filters:
  metadata_variable: "genotype" # This variable will be used throughout the whole script

metadata: 
  sample_type:
    value_QC: "QC"
    value_BK: "BK"
    value_sample: "sample"


boxplot:
  topN : 16 # N for TopN boxplots to output 

posthoc:
  p_value: 0.8 # p-Value for filtering th RF inputs

heatmap:
  topN : 150 # N for TopN features to output in the heatmap

