mapp_project : mapp_project_00007
mapp_batch : mapp_batch_00020
met_annot_enhancer_folder : mapp_batch_00020
gnps_job_id : dbb61f53ca4e4ab8bac13d4662aadd8e

dataset_experiment : 
  name: "mapp_batch_00020 LCMS metabolomics dataset"
  description: "Didier reinhardt Medicago Nodules HILIC Metabo pos"

ms_files_extension: ".mzML"

filenames:
  sirius_annotations: compound_identifications.tsv
  canopus_annotations: canopus_compound_summary.tsv
  gnps_graphml: 27ac08b3bd43408c8d7f6a8e42d51cb9.graphml


actions:
  scale_data : TRUE
  filter_sample_type : TRUE
  filter_sample_metadata_one : TRUE
  filter_sample_metadata_two : FALSE
  filter_variable_metadata_one : FALSE
  filter_variable_metadata_two : FALSE
  filter_variable_metadata_annotated : TRUE
  filter_variable_metadata_num : TRUE
  filter_features : FALSE
  run_PLSDA : TRUE
  calculate_multi_series_fc : FALSE
  run_fc_treemaps : TRUE
  set_colors_manually : TRUE


filter_sample_type :
  mode : 'include'
  factor_name : 'sample_type'
  levels : 'sample' 

filter_sample_metadata_one :
  mode : 'include'
  factor_name : 'condition_simplified'
  levels : 
      #- 'C'
      # - 'HN'
      # - 'NifH'
      # - 'Argon'
      - 'WT'
      - 'Argon_NifH'


filter_sample_metadata_two :
  mode : 'exclude'
  factor_name : 'genotype'
  levels : 'Co'

filter_variable_metadata_one :
  mode : 'include'
  factor_name : 'npc_pathway_canopus'
  levels : 'Carbohydrates' # E.g. One of "Alkaloids", "Amino acids and Peptides", "Terpenoids", "Fatty acids", "Carbohydrates", "Polyketides", "Shikimates and Phenylpropanoids" for levels if you use factor_name : 'NPC.pathway_canopus'

filter_variable_metadata_two :
  mode : 'include'
  factor_name : 'npc_pathway_canopus'
  levels : 'Fatty acids' 


filter_variable_metadata_annotated :
  mode : 'exclude'
  factor_name : 'chebiasciiname_sirius'
  levels : 'NA'

filter_variable_metadata_num :
  mode : 'above'
  factor_name : 'npc_superclass_probability_canopus'
  level : 0.8


target:
  sample_metadata_header: "condition_simplified" # This variable will be used throughout the whole script
   ## XXX_simplified  for combined horizontally


colors:
  all:
   key:
      - 'Argon'
      - 'Argon_NifH'
      - 'C'
      - 'HN'
      - 'NifH'
      - 'WT'

   value:
      - "darkslateblue" # 'Argon'
      - "darkslategray" # 'Argon_NifH'
      - "dimgray" # 'C'
      - "cadetblue" # 'HN'
      - "goldenrod" # 'NifH'
      - "darkolivegreen" # 'WT'


# Only colors without a numeric (for some reason iheatmapr appears to not like these)

# http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf

# "aliceblue", "antiquewhite", "aquamarine", "azure", "beige", "bisque", "blanchedalmond",
# "blueviolet", "brown", "burlywood", "cadetblue", "chartreuse", "chocolate", "coral",
# "cornflowerblue", "cornsilk", "crimson", "darkblue", "darkcyan", "darkgoldenrod",
# "darkgray", "darkgreen", "darkkhaki", "darkmagenta", "darkolivegreen", "darkorange",
# "darkorchid", "darkred", "darksalmon", "darkseagreen", "darkslateblue", "darkslategray",
# "darkturquoise", "darkviolet", "deeppink", "deepskyblue", "dimgray", "dodgerblue",
# "firebrick", "floralwhite", "forestgreen", "gainsboro", "ghostwhite", "gold", "goldenrod",
# "greenyellow", "honeydew", "hotpink", "indianred", "indigo", "ivory", "khaki", "lavender",
# "lavenderblush", "lawngreen", "lemonchiffon", "lightblue", "lightcoral", "lightcyan",
# "lightgoldenrodyellow", "lightgray", "lightgreen", "lightpink", "lightsalmon",
# "lightseagreen", "lightskyblue", "lightslategray", "lightsteelblue", "lightyellow",
# "limegreen", "linen", "magenta", "maroon", "mediumaquamarine", "mediumblue", "mediumorchid",
# "mediumpurple", "mediumseagreen", "mediumslateblue", "mediumspringgreen", "mediumturquoise",
# "mediumvioletred", "midnightblue", "mintcream", "mistyrose", "moccasin", "navajowhite",
# "navy", "oldlace", "olivedrab", "orange", "orangered", "orchid", "palegoldenrod",
# "palegreen", "paleturquoise", "palevioletred", "papayawhip", "peachpuff", "peru", "pink",
# "plum", "powderblue", "purple", "rosybrown", "royalblue", "saddlebrown", "salmon",
# "sandybrown", "seagreen", "seashell", "sienna", "skyblue", "slateblue", "slategray",
# "snow", "springgreen", "steelblue", "tan", "thistle", "tomato", "turquoise", "violet",
# "wheat", "whitesmoke", "yellowgreen"



# The data intensity (using DE_original, that is unscaled data) for all levels within the following list of factor_names will be meaned and outputted in their respective new columns. This can be usefull e.g. for pie charts groups used in Cytoscape.
to_mean:
  factor_name:
    - "condition"

# Here we can alter the original sample metadata file if the levels or factors have not been correctly defined in the initial file.
# First we work vertically (within a given SM column)
# The new levels will be named as follows: alphabetically ordered and separated by an underscore.
# E.g. if you choose to combine Ag and Ab the resulting level will be Ab_Ag. These will appear in a new column which will be name by the name of the original colum suffixed by '_simplified'


to_combine_vertically: 
  column1: 
    factor_name: "condition"
    groups:
      group1:
        levels: 
        - "Argon"
        - "NifH"
      group2: 
        levels:
        - "HN"
        - "C"
  # # column2: 
  #   name: "sample_type"
  #   groups:
  #     group1:
  #       cols: 
  #       - "sample"
  #       - "QC"

# Then we work horizontally (across SM columns)
# This action is restricted to rows where sample_type == "sample"
# The levels are combined row-wise using _ as separator.
# The resulting column is named by the alphabetically ordered, _ separated, combination of the combined factor_names. (e.g. genotype_period)


to_combine_horizontally:
  factor_name: 
     - "condition"



multi_series:
  # colname: 'time.point'
  # points:
  #    - '00'
  #    - '04'
  #    - '08'
  #    - '12'
  #    - '16'
  #    - '20'


boxplot:
  topN : 16 # N for TopN boxplots to output 

posthoc:
  p_value: 0.05 # p-Value for filtering th RF inputs

heatmap:
  topN : 100 # N for TopN features to output in the heatmap


feature_to_filter :