mapp_project : mapp_project_00007
mapp_batch : mapp_batch_00059
met_annot_enhancer_folder : mapp_batch_00059
gnps_job_id : b44c9fecbbe843a7ab3b25a59c2200d3

dataset_experiment : 
  name: "mapp_batch_00059 LCMS metabolomics dataset"
  description: "Didier reinhardt Medicago Nodules HILIC Metabo neg "

polarity: "neg"
ms_files_extension: ".mzML"

filenames:
  sirius_annotations: compound_identifications.tsv
  canopus_annotations: canopus_compound_summary.tsv
  gnps_graphml: c93d24007a2c4d42857c724ce15421d6.graphml

actions:
  scale_data : TRUE
  filter_sample_type : TRUE
  filter_sample_metadata_one : TRUE
  filter_sample_metadata_two : FALSE
  filter_variable_metadata_one : FALSE
  filter_variable_metadata_two : FALSE
  filter_features : FALSE
  run_PLSDA : TRUE
  calculate_multi_series_fc : FALSE
  run_fc_treemaps : TRUE

filter_sample_type :
  mode : 'include'
  factor_name : 'sample_type'
  levels : 'sample' 

filter_sample_metadata_one :
  mode : 'include'
  factor_name : 'ATTRIBUTE_condition'
  levels : 
      #- 'C'
      # - 'HN'
      - 'NifH'
      - 'Argon'
      # - 'WT'

filter_sample_metadata_two :
  mode : 'exclude'
  factor_name : 'condition'
  levels : 'C'

filter_variable_metadata_one :
  mode : 'include'
  factor_name : 'NPC.pathway_canopus'
  levels : 'Fatty acids' # E.g. One of "Alkaloids", "Amino acids and Peptides", "Terpenoids", "Fatty acids", "Carbohydrates", "Polyketides", "Shikimates and Phenylpropanoids" for levels if you use factor_name : 'NPC.pathway_canopus'

filter_variable_metadata_two :
  mode : 'include'
  factor_name : 'NPC.pathway_canopus'
  levels : 'Fatty acids' 


filters:
  metadata_variable: "ATTRIBUTE_condition" # This variable will be used throughout the whole script


colnames:
  to_combine: 
     - "ATTRIBUTE_condition"
    #  - "condition_detailed"

  to_output:
    #  - "ATTRIBUTE_condition"


to_combine_horizontally: # beware : do not use underscore in your new names !
  column1: 
    name: "condition"
    groups:
      # group1: 
      #   name: "HN_WT"
      #   cols: 
      #   - "HN"
      #   - "WT"
      # group2: 
      #   name: "ArgonNifH"
      #   cols: 
      #   - "Argon"
      #   - "NifH"
      #   #- "HN"
  # column2: 
  #   name: "sample_type"
  #   groups:
  #     group1: 
  #       name: "sample_QC"
  #       cols: 
  #       - "sample"
  #       - "QC"

multi_series:
  colname: 'time.point'
  points:
     - '00'
     - '04'
     - '08'
     - '12'
     - '16'
     - '20'


boxplot:
  topN : 16 # N for TopN boxplots to output 

posthoc:
  p_value: 0.05 # p-Value for filtering th RF inputs

heatmap:
  topN : 100 # N for TopN features to output in the heatmap


feature_to_filter :
    - '3298_214.19_6.5'
    - '3311_252.18_4'
    - '1630_229.19_7.6'
    - '1638_214.19_6.5'