mapp_project : mapp_project_00013
mapp_batch : mapp_batch_00026
met_annot_enhancer_folder : mapp_batch_00026
gnps_job_id : ae571ceb70644788ac0e14b90546275f

dataset_experiment : 
  name: "mapp_batch_00026 LCMS metabolomics dataset"
  description: "Katrin - Mice CSF - total per2"


ms_files_extension: ".mzML"

filenames:
  sirius_annotations: compound_identifications.tsv
  canopus_annotations: canopus_compound_summary.tsv
  gnps_graphml: 60b99eff119447a8b426f598c054f31c.graphml


actions:
  scale_data : TRUE
  filter_sample_type : TRUE
  filter_sample_metadata_one : TRUE
  filter_sample_metadata_two : FALSE
  filter_variable_metadata_one : FALSE
  filter_variable_metadata_two : FALSE
  filter_variable_metadata_annotated : FALSE
  filter_variable_metadata_num : TRUE
  filter_features : TRUE
  run_PLSDA : TRUE
  calculate_multi_series_fc : FALSE
  run_fc_treemaps : TRUE
  set_colors_manually : TRUE


filter_sample_type :
  mode : 'include'
  factor_name : 'sample_type'
  levels : 'sample' 

filter_sample_metadata_one :
  mode : 'include'
  factor_name : 'period'
  levels : 
    # - "Co_day"
    # - "Co_night"
    # - "KO_day"
    # - "KO_night"
    - "day"
    - "night"


filter_sample_metadata_two :
  mode : 'exclude'
  factor_name : 'genotype'
  levels : 'Co'

filter_variable_metadata_one :
  mode : 'exclude'
  factor_name : 'npc_pathway_canopus'
  levels : 'Fatty acids' # E.g. One of "Alkaloids", "Amino acids and Peptides", "Terpenoids", "Fatty acids", "Carbohydrates", "Polyketides", "Shikimates and Phenylpropanoids" for levels if you use factor_name : 'NPC.pathway_canopus'

filter_variable_metadata_two :
  mode : 'include'
  factor_name : 'npc_pathway_canopus'
  levels : 'Fatty acids' 


filter_variable_metadata_annotated :
  mode : 'exclude'
  factor_name : 'chebiasciiname_sirius'
  levels : 'NA'

filter_variable_metadata_num :
  mode : 'above'
  factor_name : 'npc_superclass_probability_canopus'
  level : 0.8


target:
  sample_metadata_header: "period" # This variable will be used throughout the whole script
   ## XXX_simplified  for combined horizontally


colors:
  all:
   key:
    - "Co_day"
    - "Co_night"
    - "KO_day"
    - "KO_night"
    - "day"
    - "night"
   value:
    - "darkorange" # Co_day
    - "darkslategrey" # Co_night
    - "goldenrod" # KO_day
    - "darkblue" # KO_night
    - "deepskyblue"
    - "darkslateblue"
  # heatmap:
  #  - "darkturquoise" # Co_night
  #  - "darkviolet" # KO_night
  # #  - "peachpuff" # Co_day
  # #  - "orange" # KO_day
  # #  - "blueviolet"
  # #  - "#fff400" # bright yellow
  # #  - "#0040b6" # dark blue
  # #  - "#a89639"
  # #  - "#b1bd7e"
  # #  - "#dd6665"
  # #  - "#dd4341"
  # volcano:
  #  - "darkturquoise" # Co_night
  #  - "darkviolet" # KO_night
  # #  - "peachpuff" # Co_day
  # #  - "orange" # KO_day
  # #  - "orange"
  # #  - "blueviolet"

# Only colors without a numeric (for some reason iheatmapr appears to not like these)

# http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf

# "aliceblue", "antiquewhite", "aquamarine", "azure", "beige", "bisque", "blanchedalmond",
# "blueviolet", "brown", "burlywood", "cadetblue", "chartreuse", "chocolate", "coral",
# "cornflowerblue", "cornsilk", "crimson", "darkblue", "darkcyan", "darkgoldenrod",
# "darkgray", "darkgreen", "darkkhaki", "darkmagenta", "darkolivegreen", "darkorange",
# "darkorchid", "darkred", "darksalmon", "darkseagreen", "darkslateblue", "darkslategray",
# "darkturquoise", "darkviolet", "deeppink", "deepskyblue", "dimgray", "dodgerblue",
# "firebrick", "floralwhite", "forestgreen", "gainsboro", "ghostwhite", "gold", "goldenrod",
# "greenyellow", "honeydew", "hotpink", "indianred", "indigo", "ivory", "khaki", "lavender",
# "lavenderblush", "lawngreen", "lemonchiffon", "lightblue", "lightcoral", "lightcyan",
# "lightgoldenrodyellow", "lightgray", "lightgreen", "lightpink", "lightsalmon",
# "lightseagreen", "lightskyblue", "lightslategray", "lightsteelblue", "lightyellow",
# "limegreen", "linen", "magenta", "maroon", "mediumaquamarine", "mediumblue", "mediumorchid",
# "mediumpurple", "mediumseagreen", "mediumslateblue", "mediumspringgreen", "mediumturquoise",
# "mediumvioletred", "midnightblue", "mintcream", "mistyrose", "moccasin", "navajowhite",
# "navy", "oldlace", "olivedrab", "orange", "orangered", "orchid", "palegoldenrod",
# "palegreen", "paleturquoise", "palevioletred", "papayawhip", "peachpuff", "peru", "pink",
# "plum", "powderblue", "purple", "rosybrown", "royalblue", "saddlebrown", "salmon",
# "sandybrown", "seagreen", "seashell", "sienna", "skyblue", "slateblue", "slategray",
# "snow", "springgreen", "steelblue", "tan", "thistle", "tomato", "turquoise", "violet",
# "wheat", "whitesmoke", "yellowgreen"


colnames:
  to_combine: 
     - "genotype"
     - "period"
     - "sex"

  to_output:
     - "genotype"
     - "period"
     - "sex"
     

to_combine_horizontally: # beware : do not use underscore in your new names !
  # column1: 
  #   name: "condition"
  #   groups:
      # group1: 
      #   name: "HN-WT"
      #   cols: 
      #   - "HN"
      #   - "WT"
  #      group2: 
  #        name: "Argon-Nifh" # This name should not be created manually but automatically concatenated (using hyphens and not underscore)
  #        cols: 
  #        - "Argon"
  #        - "NifH"
  #        - "HN"
  # # column2: 
  #   name: "sample_type"
  #   groups:
  #     group1: 
  #       name: "sample_QC"
  #       cols: 
  #       - "sample"
  #       - "QC"

multi_series:
  colname: 'time.point'
  points:
     - '00'
     - '04'
     - '08'
     - '12'
     - '16'
     - '20'


boxplot:
  topN : 16 # N for TopN boxplots to output 

posthoc:
  p_value: 0.05 # p-Value for filtering th RF inputs

heatmap:
  topN : 100 # N for TopN features to output in the heatmap


feature_to_filter :
  - '3298'
  - '3311'
  - '1630'
  - '1638'
  - '3299'
  - '3306'
  - '3058'
  - '1598'
  - '1941'
  - '4046'
  - '4047'
  - '1580'
  - '2705'
  - '1627'
  - '1617'
  - '1600'
  - '1606'
  - '3980'
  - '3302'
  - '253'
  - '3090'
  - '1585'
  - '1601'
  - '1688'
  - '3241'
  - '2203'
  - '3803'
  - '4506'
  - '3305'
  - '1620'
  - '2818'
  - '1619'
  - '1634'
  - '2829'
  - '2270'
  - '1649'
  - '4625'
  - '2815'
  - '3077'
  - '3303'
  - '1610'
  - '1612'
  - '1771'
  - '1578'
  - '1590'
  - '2278'
  - '1770'
  - '1700'
  - '1775'
  - '2006'
  - '1957'
  - '3211'
  - '1808'
  - '4473'
  - '1587'
  - '1583'
  - '1631'
  - '1915'
  - '2768'
  - '2868'
  - '1806'
  - '3924'
  - '3195'
  - '3828'
  - '1642'
  - '3901'
  - '2802'
  - '1922'
  - '2692'
  - '1698'
  - '1621'
  - '1633'
  - '3125'
  - '1607'
  - '1759'
  - '2679'
  - '4015'
  - '1608'
  - '2010'
  - '1689'
  - '1618'
  - '1658'
  - '1680'
  - '1880'
  - '1998'
  - '2846'
  - '1648'
  - '4022'
  - '1652'
  - '1640'
  - '3078'
  - '1917'
  - '1953'
  - '2673'
  - '1644'
  - '1637'
  - '1683'
  - '1639'
  - '1645'
  - '4029'
  - '1852'
  - '1659'
  - '1722'
  - '2693'
  - '1611'
  - '900'
  - '1667'
  - '2756'
  - '1609'
  - '1884'
  - '1673'
  - '691'
  - '2764'
  - '3091'
  - '1591'
  - '1632'
  - '1604'
  - '2011'
  - '1624'
  - '1841'
  - '2808'
  - '3420'
  - '2843'
  - '3084'
  - '1702'
  - '1772'
  - '1665'
  - '2854'
  - '2483'
  - '3098'
  - '4227'
  - '3580'
  - '3099'
  - '1605'
  - '1615'
  - '1760'
  - '3095'
  - '3059'
  - '1766'
  - '4019'
  - '1671'
  - '3130'
  - '1646'
  - '2763'
  - '2037'
  - '2812'
  - '1662'
  - '3097'
  - '4196'
  - '1748'
  - '3440'
  - '1695'
  - '1577'
  - '3332'
  - '1684'
  - '1657'
  - '1581'
  - '1616'
  - '2798'
  - '2276'
  - '2862'
  - '4620'
  - '1588'
  - '2035'
  - '2000'
  - '3071'
  - '1813'
  - '1676'
  - '1740'
  - '2742'
  - '2678'
  - '1593'
  - '3138'
  - '896'
  - '1682'
  - '1622'
  - '379'
  - '122'
  - '3072'
  - '1675'
  - '2247'
  - '2837'
  - '3237'
  - '3074'
  - '1709'
  - '1408'
  - '3899'
  - '2083'
  - '1635'
  - '1654'
  - '837'
  - '2156'
  - '228'
  - '3045'
  - '3295'
  - '2790'
  - '139'
  - '2074'
  - '164'
  - '710'
  - '2806'
  - '2850'
  - '3036'
  - '152'
  - '3043'
  - '3354'
  - '2161'
  - '1134'
  - '220'
  - '2949'
  - '1292'
  - '2835'
  - '1586'
  - '4210'
  - '2515'
  - '963'
  - '2025'
  - '2026'
  - '4017'
