mapp_project : mapp_project_00017
mapp_batch : mapp_batch_00044
met_annot_enhancer_folder : mapp_batch_00044
gnps_job_id : d53d09cdd2c04fd2961724cb136cfe61

dataset_experiment : 
  name: "mapp_batch_00044 LCMS metabolomics dataset"
  description: "Simon Blanchoud Tunicates metabo pos "

paths:
  docs: 'G:/Mon Drive/taf/git_repository/simon-blanchoud-group/docs'
  output: 'G:/Mon Drive/taf/git_repository/simon-blanchoud-group/docs/MAPP_project_00017/mapp_batch_00044/pos/results/tmp' # Not mandatory, default is in the stats subdirectory

actions:
  scale_data : TRUE
  filter_sample_type : TRUE
  filter_sample_metadata_one : FALSE
  filter_sample_metadata_two : FALSE
  filter_variable_metadata_one : FALSE
  filter_variable_metadata_two : FALSE
  filter_features : FALSE
  run_PLSDA : TRUE
  calculate_multi_series_fc : FALSE

filter_sample_type :
  mode : 'include'
  factor_name : 'sample_type'
  levels : 'sample' 

filter_sample_metadata_one :
  mode : 'exclude'
  factor_name : 'period'
  levels : 'inter'

filter_sample_metadata_two :
  mode : 'include'
  factor_name : 'period'
  levels : 'night'

filter_variable_metadata_one :
  mode : 'include'
  factor_name : 'NPC.pathway_canopus'
  levels : 'Fatty acids' # E.g. One of "Alkaloids", "Amino acids and Peptides", "Terpenoids", "Fatty acids", "Carbohydrates", "Polyketides", "Shikimates and Phenylpropanoids" for levels if you use factor_name : 'NPC.pathway_canopus'

filter_variable_metadata_two :
  mode : 'include'
  factor_name : 'NPC.pathway_canopus'
  levels : 'Fatty acids' 


polarity: "pos"
ms_files_extension: ".mzML"

filenames:
  sirius_annotations: compound_identifications.tsv
  canopus_annotations: canopus_compound_summary.tsv
  gnps_graphml: e1369f2f08f041218f24d0cf4b085f7c.graphml

colnames:
  to_combine: 
     - "process"

  to_output:
     - "process"


multi_series:
  colname: 'time.point'
  points:
     - '00'
     - '04'
     - '08'
     - '12'
     - '16'
     - '20'

     
filters:
  metadata_variable: "process" # This variable will be used throughout the whole script

boxplot:
  topN : 16 # N for TopN boxplots to output 

posthoc:
  p_value: 0.05 # p-Value for filtering th RF inputs

heatmap:
  topN : 100 # N for TopN features to output in the heatmap


feature_to_filter :
    - '3298_214.19_6.5'
    - '3311_252.18_4'
    - '1630_229.19_7.6'
    - '1638_214.19_6.5'
    